# Build settings
remote_theme: jekyll-theme-cayman-blog
markdown: kramdown

# basic options
title: SmartLoad
author: Keshav Vasudevan
email: keshav.vasudevan@smartbear.com
description: SmartLoad is the performance testing tool that drastically minimizes your load testing efforts and maximizes your app’s reliability
twitter_username: SmartBear
github_username: SmartBear
repository: SmartBear/smartload-www
